const mongoose = require("mongoose");

const studentSchema = new mongoose.Schema({
  studentId: { type: String, required: true, unique: true }, // IMPORTANT
  admitClass: String,
  section: String,
  rollNo: String,
  firstName: String,
  lastName: String,
  gender: String,
  socialCaste: String,
  dob: String,
  height: String,
  weight: String,
  bloodGroup: String,
  brothers: String,
  sisters: String,
  nationality: String,
  languages: [String],
  permanentAddress: {
    vill: String,
    po: String,
    block: String,
    pin: String,
    ps: String,
    dist: String,
  },
  currentAddress: {
    vill: String,
    po: String,
    block: String,
    pin: String,
    ps: String,
    dist: String,
  },
  transportRequired: String,
  distanceFromSchool: String,
  emergencyContact: String,
  emergencyPerson: String,
  fatherName: String,
  fatherOccupation: String,
  fatherPhone: String,
  fatherEmail: String,
  fatherNationality: String,
  fatherQualification: String,
  motherName: String,
  motherOccupation: String,
  motherPhone: String,
  motherEmail: String,
  motherNationality: String,
  motherQualification: String,
  bpl: String,
  bplNo: String,
  familyIncome: String,
});

module.exports = mongoose.model("Student", studentSchema);
